name: penta_core
description: "A package for Penta Core, a Flutter package that provides a set of utilities and tools to help developers build high-quality applications quickly and efficiently."
version: 2.1.0
homepage: https://github.com/ANILSRGT
repository: https://github.com/ANILSRGT/flutter_penta_core
license: MIT

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Used for check the internet connection
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  path: ^1.9.1
  source_gen: ^3.0.0
  build: ^3.0.0
  ansicolor: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

executables:
  lang_generator: lang_generator
